language: php

dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.2
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.2

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --verbose
